### ISSUE TITLE
please make this app have same functionallity as nextcloud bookmarks v0.10.1

### ISSUE THREAD

**Issue by theScrabi** [mondjunge/bookmarks#2]
Hello,

[v0.10.1](https://github.com/nextcloud/bookmarks/tree/293e7123d9c92f0730a46a44b96b5545b297814d) of the nextcloud version of bookmarks already supports a more advanced REST api, which is necessary for several external apps to work.
It would be nice if this nextcloud version could be merged with this one :)

rgds Schabi

**Comment by mondjunge** [comment]
I just uploaded version 0.10.2 to the marketplace which includes all the latest nextcloud/bookmark changes.

Have fun and report bugs. :)
